// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'izin_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_IzinList _$$_IzinListFromJson(Map<String, dynamic> json) => _$_IzinList(
      idIzin: json['id_izin'] as int?,
      idUser: json['id_user'] as int?,
      idDept: json['id_dept'] as int?,
      ket: json['ket'] as String?,
      tglStart: json['tgl_start'] as String?,
      tglEnd: json['tgl_end'] as String?,
      spvSta: json['spv_sta'] as bool?,
      spvNm: json['spv_nm'] as String?,
      spvTgl: json['spv_tgl'] as String?,
      hrdSta: json['hrd_sta'] as bool?,
      hrdNm: json['hrd_nm'] as String?,
      hrdTgl: json['hrd_tgl'] as String?,
      cDate: json['c_date'] as String?,
      cUser: json['c_user'] as String?,
      uDate: json['u_date'] as String?,
      uUser: json['u_user'] as String?,
      hrdNote: json['hrd_note'] as String?,
      spvNote: json['spv_note'] as String?,
      tglStartHrd: json['tgl_start_hrd'] as String?,
      tglEndHrd: json['tgl_end_hrd'] as String?,
      totHari: json['tot_hari'] as int?,
      btlSta: json['btl_sta'] as bool?,
      btlTgl: json['btl_tgl'] as String?,
      btlNm: json['btl_nm'] as String?,
      idMstIzin: json['id_mst_izin'] as int?,
      qtyfoto: json['qtyfoto'] as int?,
      namaIzin: json['namaIzin'] as String?,
      appSpv: json['app_spv'] as String?,
      appHrd: json['app_hrd'] as String?,
      uBy: json['u_by'] as String?,
      cBy: json['c_by'] as String?,
      idkar: json['idkar'] as String?,
      payroll: json['payroll'] as String?,
      noTelp1: json['no_telp1'] as String?,
      noTelp2: json['no_telp2'] as String?,
      fullname: json['fullname'] as String?,
      dept: json['dept'] as String?,
      comp: json['comp'] as String?,
    );

Map<String, dynamic> _$$_IzinListToJson(_$_IzinList instance) =>
    <String, dynamic>{
      'id_izin': instance.idIzin,
      'id_user': instance.idUser,
      'id_dept': instance.idDept,
      'ket': instance.ket,
      'tgl_start': instance.tglStart,
      'tgl_end': instance.tglEnd,
      'spv_sta': instance.spvSta,
      'spv_nm': instance.spvNm,
      'spv_tgl': instance.spvTgl,
      'hrd_sta': instance.hrdSta,
      'hrd_nm': instance.hrdNm,
      'hrd_tgl': instance.hrdTgl,
      'c_date': instance.cDate,
      'c_user': instance.cUser,
      'u_date': instance.uDate,
      'u_user': instance.uUser,
      'hrd_note': instance.hrdNote,
      'spv_note': instance.spvNote,
      'tgl_start_hrd': instance.tglStartHrd,
      'tgl_end_hrd': instance.tglEndHrd,
      'tot_hari': instance.totHari,
      'btl_sta': instance.btlSta,
      'btl_tgl': instance.btlTgl,
      'btl_nm': instance.btlNm,
      'id_mst_izin': instance.idMstIzin,
      'qtyfoto': instance.qtyfoto,
      'namaIzin': instance.namaIzin,
      'app_spv': instance.appSpv,
      'app_hrd': instance.appHrd,
      'u_by': instance.uBy,
      'c_by': instance.cBy,
      'idkar': instance.idkar,
      'payroll': instance.payroll,
      'no_telp1': instance.noTelp1,
      'no_telp2': instance.noTelp2,
      'fullname': instance.fullname,
      'dept': instance.dept,
      'comp': instance.comp,
    };
