// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tugas_dinas_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_TugasDinasList _$$_TugasDinasListFromJson(Map<String, dynamic> json) =>
    _$_TugasDinasList(
      idDinas: json['id_dinas'] as int,
      idUser: json['id_user'] as int,
      ket: json['ket'] as String?,
      tglStart: json['tgl_start'] as String?,
      tglEnd: json['tgl_end'] as String?,
      spvSta: json['spv_sta'] as bool,
      spvNm: json['spv_nm'] as String?,
      spvTgl: json['spv_tgl'] as String?,
      hrdSta: json['hrd_sta'] as bool,
      hrdNm: json['hrd_nm'] as String?,
      hrdTgl: json['hrd_tgl'] as String?,
      cDate: json['c_date'] as String?,
      cUser: json['c_user'] as String?,
      uDate: json['u_date'] as String?,
      uUser: json['u_user'] as String?,
      kategori: json['kategori'] as String?,
      perusahaan: json['perusahaan'] as String?,
      lokasi: json['lokasi'] as String?,
      cooSta: json['coo_sta'] as bool,
      cooNm: json['coo_nm'] as String?,
      cooTgl: json['coo_tgl'] as String?,
      idComp: json['id_comp'] as int,
      idDept: json['id_dept'] as int,
      ittenSta: json['itten_sta'] as bool,
      reportSta: json['report_sta'] as bool,
      ittenAppNm: json['itten_app_nm'],
      reportAppNm: json['report_app_nm'],
      ittenAppTgl: json['itten_app_tgl'] as String?,
      reportAppTgl: json['report_app_tgl'] as String?,
      idPemberi: json['id_pemberi'] as int,
      gmSta: json['gm_sta'] as bool,
      gmNm: json['gm_nm'] as String?,
      gmTgl: json['gm_tgl'] as String?,
      btlSta: json['btl_sta'] as bool,
      btlTgl: json['btl_tgl'],
      btlNm: json['btl_nm'],
      jenis: json['jenis'] as bool,
      biayaSta: json['biaya_sta'] as bool,
      biayaTgl: json['biaya_tgl'],
      biayaNm: json['biaya_nm'],
      gaBiayaSta: json['ga_biaya_sta'] as bool,
      gaBiayaDate: json['ga_biaya_date'],
      gaBiayaNm: json['ga_biaya_nm'],
      jamStart: json['jam_start'] as String?,
      jamEnd: json['jam_end'] as String?,
      appSpv: json['app_spv'] as String?,
      appHrd: json['app_hrd'] as String?,
      uBy: json['u_by'] as String?,
      cBy: json['c_by'] as String?,
      pemberi: json['pemberi'] as String?,
      levelUser: json['level_user'] as int,
      idKar: json['idkar'] as String?,
      idDept1: json['id_dept1'] as int,
      payroll: json['payroll'] as String?,
      noTelp1: json['noTelp1'] as String?,
      noTelp2: json['no_telp2'] as String?,
      fullname: json['fullname'] as String?,
      dept: json['dept'] as String?,
      comp: json['comp'] as String?,
    );

Map<String, dynamic> _$$_TugasDinasListToJson(_$_TugasDinasList instance) =>
    <String, dynamic>{
      'id_dinas': instance.idDinas,
      'id_user': instance.idUser,
      'ket': instance.ket,
      'tgl_start': instance.tglStart,
      'tgl_end': instance.tglEnd,
      'spv_sta': instance.spvSta,
      'spv_nm': instance.spvNm,
      'spv_tgl': instance.spvTgl,
      'hrd_sta': instance.hrdSta,
      'hrd_nm': instance.hrdNm,
      'hrd_tgl': instance.hrdTgl,
      'c_date': instance.cDate,
      'c_user': instance.cUser,
      'u_date': instance.uDate,
      'u_user': instance.uUser,
      'kategori': instance.kategori,
      'perusahaan': instance.perusahaan,
      'lokasi': instance.lokasi,
      'coo_sta': instance.cooSta,
      'coo_nm': instance.cooNm,
      'coo_tgl': instance.cooTgl,
      'id_comp': instance.idComp,
      'id_dept': instance.idDept,
      'itten_sta': instance.ittenSta,
      'report_sta': instance.reportSta,
      'itten_app_nm': instance.ittenAppNm,
      'report_app_nm': instance.reportAppNm,
      'itten_app_tgl': instance.ittenAppTgl,
      'report_app_tgl': instance.reportAppTgl,
      'id_pemberi': instance.idPemberi,
      'gm_sta': instance.gmSta,
      'gm_nm': instance.gmNm,
      'gm_tgl': instance.gmTgl,
      'btl_sta': instance.btlSta,
      'btl_tgl': instance.btlTgl,
      'btl_nm': instance.btlNm,
      'jenis': instance.jenis,
      'biaya_sta': instance.biayaSta,
      'biaya_tgl': instance.biayaTgl,
      'biaya_nm': instance.biayaNm,
      'ga_biaya_sta': instance.gaBiayaSta,
      'ga_biaya_date': instance.gaBiayaDate,
      'ga_biaya_nm': instance.gaBiayaNm,
      'jam_start': instance.jamStart,
      'jam_end': instance.jamEnd,
      'app_spv': instance.appSpv,
      'app_hrd': instance.appHrd,
      'u_by': instance.uBy,
      'c_by': instance.cBy,
      'pemberi': instance.pemberi,
      'level_user': instance.levelUser,
      'idkar': instance.idKar,
      'id_dept1': instance.idDept1,
      'payroll': instance.payroll,
      'noTelp1': instance.noTelp1,
      'no_telp2': instance.noTelp2,
      'fullname': instance.fullname,
      'dept': instance.dept,
      'comp': instance.comp,
    };
