import 'package:freezed_annotation/freezed_annotation.dart';

part 'tugas_dinas_list.freezed.dart';
part 'tugas_dinas_list.g.dart';

@freezed
class TugasDinasList with _$TugasDinasList {
  const factory TugasDinasList({
    @JsonKey(name: 'id_dinas') int? idDinas,
    @JsonKey(name: 'id_user') int? idUser,
    String? ket,
    @JsonKey(name: 'tgl_start') DateTime? tglStart,
    @JsonKey(name: 'tgl_end') DateTime? tglEnd,
    @JsonKey(name: 'spv_sta') bool? spvSta,
    @JsonKey(name: 'spv_nm') String? spvNm,
    @JsonKey(name: 'spv_tgl') DateTime? spvTgl,
    @JsonKey(name: 'hrd_sta') bool? hrdSta,
    @JsonKey(name: 'hrd_nm') String? hrdNm,
    @JsonKey(name: 'hrd_tgl') DateTime? hrdTgl,
    @JsonKey(name: 'c_date') DateTime? cDate,
    @JsonKey(name: 'c_user') String? cUser,
    @JsonKey(name: 'u_date') DateTime? uDate,
    @JsonKey(name: 'u_user') String? uUser,
    String? kategori,
    String? perusahaan,
    String? lokasi,
    @JsonKey(name: 'coo_sta') bool? cooSta,
    @JsonKey(name: 'coo_nm') String? cooNm,
    @JsonKey(name: 'coo_tgl') DateTime? cooTgl,
    @JsonKey(name: 'id_comp') int? idComp,
    @JsonKey(name: 'id_dept') int? idDept,
    @JsonKey(name: 'itten_sta') bool? ittenSta,
    @JsonKey(name: 'report_sta') bool? reportSta,
    @JsonKey(name: 'itten_app_nm') String? ittenAppNm,
    @JsonKey(name: 'report_app_nm') String? reportAppNm,
    @JsonKey(name: 'itten_app_tgl') DateTime? ittenAppTgl,
    @JsonKey(name: 'report_app_tgl') DateTime? reportAppTgl,
    @JsonKey(name: 'id_pemberi') int? idPemberi,
    @JsonKey(name: 'gm_sta') bool? gmSta,
    @JsonKey(name: 'gm_nm') String? gmNm,
    @JsonKey(name: 'gm_tgl') DateTime? gmTgl,
    @JsonKey(name: 'btl_sta') bool? btlSta,
    @JsonKey(name: 'btl_tgl') DateTime? btlTgl,
    @JsonKey(name: 'btl_nm') String? btlNm,
    bool? jenis,
    @JsonKey(name: 'biaya_sta') bool? biayaSta,
    @JsonKey(name: 'biaya_tgl') DateTime? biayaTgl,
    @JsonKey(name: 'biaya_nm') String? biayaNm,
    @JsonKey(name: 'ga_biaya_sta') bool? gaBiayaSta,
    @JsonKey(name: 'ga_biaya_date') DateTime? gaBiayaDate,
    @JsonKey(name: 'ga_biaya_nm') String? gaBiayaNm,
    @JsonKey(name: 'jam_start') DateTime? jamStart,
    @JsonKey(name: 'jam_end') DateTime? jamEnd,
    @JsonKey(name: 'id_cuti') int? idCuti,
    @JsonKey(name: 'IdKary') String? idKary,
    String? fullname,
    String? dept,
    String? comp,
    String? email,
    @JsonKey(name: 'email2') String? email2,
    @JsonKey(name: 'level_user') int? levelUser,
    @JsonKey(name: 'agingspv') int? agingSpv,
    @JsonKey(name: 'aginghr') int? agingHr,
    @JsonKey(name: 'aginggm') int? agingGm,
    @JsonKey(name: 'agingcoo') int? agingCoo,
    @JsonKey(name: 'spv_app') String? spvApp,
    @JsonKey(name: 'hrd_app') String? hrdApp,
    @JsonKey(name: 'coo_app') String? cooApp,
    @JsonKey(name: 'gm_app') String? gmApp,
    @JsonKey(name: 'u_by') String? uBy,
    @JsonKey(name: 'c_by') String? cBy,
    @JsonKey(name: 'is_edit') bool? isEdit,
    @JsonKey(name: 'is_delete') bool? isDelete,
    @JsonKey(name: 'is_spv_note') bool? isSpvNote,
    @JsonKey(name: 'is_hr_note') bool? isHrNote,
    @JsonKey(name: 'is_spv') bool? isSpv,
    @JsonKey(name: 'spv_msg') String? spvMsg,
    @JsonKey(name: 'is_hr') bool? isHr,
    @JsonKey(name: 'hr_msg') String? hrMsg,
    @JsonKey(name: 'is_gm') bool? isGm,
    @JsonKey(name: 'gm_msg') String? gmMsg,
    @JsonKey(name: 'is_coo') bool? isCoo,
    @JsonKey(name: 'coo_msg') String? cooMsg,
    @JsonKey(name: 'is_btl') bool? isBtl,
    @JsonKey(name: 'btl_msg') String? btlMsg,
    @JsonKey(name: 'is_vis_coogm') bool? isCooGmVisible,
  }) = _TugasDinasList;

  factory TugasDinasList.fromJson(Map<String, dynamic> json) =>
      _$TugasDinasListFromJson(json);
}
