// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: non_constant_identifier_names

part of 'ganti_hari_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_GantiHariList _$$_GantiHariListFromJson(Map<String, dynamic> json) =>
    _$_GantiHariList(
      idDayoff: json['id_dayoff'] as int,
      idUser: json['id_user'] as int,
      ket: json['ket'] as String,
      tglStart: json['tgl_start'] as String,
      tglEnd: json['tgl_end'] as String,
      spvSta: json['spv_sta'] as bool,
      spvNm: json['spv_nm'] as String,
      spvTgl: json['spv_tgl'] as String,
      hrdSta: json['hrd_sta'] as bool,
      hrdNm: json['hrd_nm'] as String,
      hrdTgl: json['hrd_tgl'] as String,
      cDate: json['c_date'] as String,
      cUser: json['c_user'] as String,
      uDate: json['u_date'] as String,
      uUser: json['u_user'] as String,
      idComp: json['id_comp'] as int,
      idDept: json['id_dept'] as int,
      cooSta: json['coo_sta'] as bool,
      cooNm: json['coo_nm'] as String,
      cooTgl: json['coo_tgl'] as String,
      ittenSta: json['itten_sta'] as bool,
      reportSta: json['report_sta'] as bool,
      ittenAppNm: json['itten_app_nm'] as String,
      reportAppNm: json['report_app_nm'] as String,
      ittenAppTgl: json['itten_app_tgl'] as String,
      reportAppTgl: json['report_app_tgl'] as String,
      idPemberi: json['id_pemberi'] as String,
      gmSta: json['gm_sta'] as bool,
      gmNm: json['gm_nm'] as String,
      gmTgl: json['gm_tgl'] as String,
      btlSta: json['btl_sta'] as bool,
      btlTgl: json['btl_tgl'] as String,
      btlNm: json['btl_nm'] as String,
      jenis: json['jenis'] as bool,
      biayaSta: json['biaya_sta'] as bool,
      biayaTgl: json['biaya_tgl'] as String,
      biayaNm: json['biaya_nm'] as String,
      gaBiayaSta: json['ga_biaya_sta'] as bool,
      gaBiayaDate: json['ga_biaya_date'] as String,
      gaBiayaNm: json['ga_biaya_nm'] as String,
      idMstDayoff: json['id_mst_dayoff'] as String,
      jamStart: json['jam_start'] as String,
      jamEnd: json['jam_end'] as String,
      idAbsen: json['id_absen'] as String,
      idKary: json['IdKary'] as String,
      spvApp1: json['spv_app1'] as String,
      hrdApp1: json['hrd_app1'] as String,
      cooApp1: json['coo_app1'] as String,
      gmApp1: json['gm_app1'] as String,
      uBy: json['u_by'] as String,
      cBy: json['c_by'] as String,
      levelUser: json['level_user'] as int,
      noTelp1: json['no_telp1'] as String,
      noTelp2: json['no_telp2'] as String,
      fullname: json['fullname'] as String,
      dept: json['dept'] as String,
      comp: json['comp'] as String,
    );

Map<String, dynamic> _$$_GantiHariListToJson(_$_GantiHariList instance) =>
    <String, dynamic>{
      'id_dayoff': instance.idDayoff,
      'id_user': instance.idUser,
      'ket': instance.ket,
      'tgl_start': instance.tglStart,
      'tgl_end': instance.tglEnd,
      'spv_sta': instance.spvSta,
      'spv_nm': instance.spvNm,
      'spv_tgl': instance.spvTgl,
      'hrd_sta': instance.hrdSta,
      'hrd_nm': instance.hrdNm,
      'hrd_tgl': instance.hrdTgl,
      'c_date': instance.cDate,
      'c_user': instance.cUser,
      'u_date': instance.uDate,
      'u_user': instance.uUser,
      'id_comp': instance.idComp,
      'id_dept': instance.idDept,
      'coo_sta': instance.cooSta,
      'coo_nm': instance.cooNm,
      'coo_tgl': instance.cooTgl,
      'itten_sta': instance.ittenSta,
      'report_sta': instance.reportSta,
      'itten_app_nm': instance.ittenAppNm,
      'report_app_nm': instance.reportAppNm,
      'itten_app_tgl': instance.ittenAppTgl,
      'report_app_tgl': instance.reportAppTgl,
      'id_pemberi': instance.idPemberi,
      'gm_sta': instance.gmSta,
      'gm_nm': instance.gmNm,
      'gm_tgl': instance.gmTgl,
      'btl_sta': instance.btlSta,
      'btl_tgl': instance.btlTgl,
      'btl_nm': instance.btlNm,
      'jenis': instance.jenis,
      'biaya_sta': instance.biayaSta,
      'biaya_tgl': instance.biayaTgl,
      'biaya_nm': instance.biayaNm,
      'ga_biaya_sta': instance.gaBiayaSta,
      'ga_biaya_date': instance.gaBiayaDate,
      'ga_biaya_nm': instance.gaBiayaNm,
      'id_mst_dayoff': instance.idMstDayoff,
      'jam_start': instance.jamStart,
      'jam_end': instance.jamEnd,
      'id_absen': instance.idAbsen,
      'IdKary': instance.idKary,
      'spv_app1': instance.spvApp1,
      'hrd_app1': instance.hrdApp1,
      'coo_app1': instance.cooApp1,
      'gm_app1': instance.gmApp1,
      'u_by': instance.uBy,
      'c_by': instance.cBy,
      'level_user': instance.levelUser,
      'no_telp1': instance.noTelp1,
      'no_telp2': instance.noTelp2,
      'fullname': instance.fullname,
      'dept': instance.dept,
      'comp': instance.comp,
    };
