// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: non_constant_identifier_names

part of 'absen_manual_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_AbsenManualList _$$_AbsenManualListFromJson(Map<String, dynamic> json) =>
    _$_AbsenManualList(
      idAbsenmnl: json['id_absenmnl'] as int,
      idUser: json['id_user'] as int,
      tgl: json['tgl'] as String?,
      jamAwal: json['jam_awal'] as String?,
      jamAkhir: json['jam_akhir'] as String?,
      ket: json['ket'] as String?,
      cDate: json['c_date'] as String?,
      cUser: json['c_user'] as String?,
      uDate: json['u_date'] as String?,
      uUser: json['u_user'] as String?,
      spvSta: json['spv_sta'] as bool,
      spvNm: json['spv_nm'] as String?,
      spvTgl: json['spv_tgl'] as String?,
      hrdSta: json['hrd_sta'] as bool,
      hrdNm: json['hrd_nm'] as String?,
      hrdTgl: json['hrd_tgl'] as String?,
      btlSta: json['btl_sta'] as bool,
      btlNm: json['btl_nm'] as String?,
      btlTgl: json['btl_tgl'] as String?,
      spvNote: json['spv_note'] as String?,
      hrdNote: json['hrd_note'] as String?,
      periode: json['periode'] as String?,
      jenisAbsen: json['jenis_absen'] as String?,
      latitudeMasuk: json['latitude_masuk'],
      longtitudeMasuk: json['longtitude_masuk'],
      latitudeKeluar: json['latitude_keluar'],
      longtitudeKeluar: json['longtitude_keluar'],
      lokasiMasuk: json['lokasi_masuk'],
      lokasiKeluar: json['lokasi_keluar'],
      appSpv: json['app_spv'] as String?,
      appHrd: json['app_hrd'] as String?,
      uBy: json['u_by'] as String?,
      cBy: json['c_by'] as String?,
      idKar: json['idkar'] as String?,
      idDept: json['id_dept'] as int,
      payroll: json['payroll'] as String?,
      noTelp1: json['no_telp1'] as String?,
      noTelp2: json['no_telp2'] as String?,
      fullname: json['fullname'] as String?,
      dept: json['dept'] as String?,
      comp: json['comp'] as String?,
    );

Map<String, dynamic> _$$_AbsenManualListToJson(_$_AbsenManualList instance) =>
    <String, dynamic>{
      'id_absenmnl': instance.idAbsenmnl,
      'id_user': instance.idUser,
      'tgl': instance.tgl,
      'jam_awal': instance.jamAwal,
      'jam_akhir': instance.jamAkhir,
      'ket': instance.ket,
      'c_date': instance.cDate,
      'c_user': instance.cUser,
      'u_date': instance.uDate,
      'u_user': instance.uUser,
      'spv_sta': instance.spvSta,
      'spv_nm': instance.spvNm,
      'spv_tgl': instance.spvTgl,
      'hrd_sta': instance.hrdSta,
      'hrd_nm': instance.hrdNm,
      'hrd_tgl': instance.hrdTgl,
      'btl_sta': instance.btlSta,
      'btl_nm': instance.btlNm,
      'btl_tgl': instance.btlTgl,
      'spv_note': instance.spvNote,
      'hrd_note': instance.hrdNote,
      'periode': instance.periode,
      'jenis_absen': instance.jenisAbsen,
      'latitude_masuk': instance.latitudeMasuk,
      'longtitude_masuk': instance.longtitudeMasuk,
      'latitude_keluar': instance.latitudeKeluar,
      'longtitude_keluar': instance.longtitudeKeluar,
      'lokasi_masuk': instance.lokasiMasuk,
      'lokasi_keluar': instance.lokasiKeluar,
      'app_spv': instance.appSpv,
      'app_hrd': instance.appHrd,
      'u_by': instance.uBy,
      'c_by': instance.cBy,
      'idkar': instance.idKar,
      'id_dept': instance.idDept,
      'payroll': instance.payroll,
      'no_telp1': instance.noTelp1,
      'no_telp2': instance.noTelp2,
      'fullname': instance.fullname,
      'dept': instance.dept,
      'comp': instance.comp,
    };
