// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dt_pc_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_DtPcList _$$_DtPcListFromJson(Map<String, dynamic> json) => _$_DtPcList(
      idDt: json['id_dt'] as int?,
      idUser: json['id_user'] as int?,
      ket: json['ket'] as String?,
      dtTgl: json['dt_tgl'] as String?,
      jam: json['jam'] as String?,
      spvSta: json['spv_sta'] as bool?,
      spvNm: json['spv_nm'] as String?,
      spvTgl: json['spv_tgl'] as String?,
      hrdSta: json['hrd_sta'] as bool?,
      hrdNm: json['hrd_nm'] as String?,
      hrdTgl: json['hrd_tgl'] as String?,
      cDate: json['c_date'] as String?,
      cUser: json['c_user'] as String?,
      uDate: json['u_date'] as String?,
      uUser: json['u_user'] as String?,
      kategori: json['kategori'] as String?,
      spvNote: json['spv_note'] as String?,
      hrdNote: json['hrd_note'] as String?,
      periode: json['periode'] as String?,
      btlSta: json['btl_sta'] as bool?,
      btlNm: json['btl_nm'] as String?,
      btlTgl: json['btl_tgl'] as String?,
      appSpv: json['app_spv'] as String?,
      appHrd: json['app_hrd'] as String?,
      uBy: json['u_by'] as String?,
      cBy: json['c_by'] as String?,
      idkar: json['idkar'] as String?,
      idDept: json['id_dept'] as int?,
      payroll: json['payroll'] as String?,
      noTelp1: json['no_telp1'] as String?,
      noTelp2: json['no_telp2'] as String?,
      fullname: json['fullname'] as String?,
      dept: json['dept'] as String?,
      comp: json['comp'] as String?,
    );

Map<String, dynamic> _$$_DtPcListToJson(_$_DtPcList instance) =>
    <String, dynamic>{
      'id_dt': instance.idDt,
      'id_user': instance.idUser,
      'ket': instance.ket,
      'dt_tgl': instance.dtTgl,
      'jam': instance.jam,
      'spv_sta': instance.spvSta,
      'spv_nm': instance.spvNm,
      'spv_tgl': instance.spvTgl,
      'hrd_sta': instance.hrdSta,
      'hrd_nm': instance.hrdNm,
      'hrd_tgl': instance.hrdTgl,
      'c_date': instance.cDate,
      'c_user': instance.cUser,
      'u_date': instance.uDate,
      'u_user': instance.uUser,
      'kategori': instance.kategori,
      'spv_note': instance.spvNote,
      'hrd_note': instance.hrdNote,
      'periode': instance.periode,
      'btl_sta': instance.btlSta,
      'btl_nm': instance.btlNm,
      'btl_tgl': instance.btlTgl,
      'app_spv': instance.appSpv,
      'app_hrd': instance.appHrd,
      'u_by': instance.uBy,
      'c_by': instance.cBy,
      'idkar': instance.idkar,
      'id_dept': instance.idDept,
      'payroll': instance.payroll,
      'no_telp1': instance.noTelp1,
      'no_telp2': instance.noTelp2,
      'fullname': instance.fullname,
      'dept': instance.dept,
      'comp': instance.comp,
    };
