// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: non_constant_identifier_names

part of 'cuti_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_CutiList _$$_CutiListFromJson(Map<String, dynamic> json) => _$_CutiList(
      idCuti: json['id_cuti'] as int?,
      idUser: json['id_user'] as int?,
      idKary: json['IdKary'] as String?,
      jenisCuti: json['jenis_cuti'] as String?,
      alasan: json['alasan'] as String?,
      ket: json['ket'] as String?,
      bulanCuti: json['bulan_cuti'] as String?,
      tahunCuti: json['tahun_cuti'] as String?,
      totalHari: json['total_hari'] as int?,
      sisaCuti: json['sisa_cuti'] as int?,
      tglStart: json['tgl_start'] as String?,
      tglEnd: json['tgl_end'] as String?,
      tglStartHrd: json['tgl_start_hrd'] as String?,
      tglEndHrd: json['tgl_end_hrd'] as String?,
      spvSta: json['spv_sta'] as bool?,
      spvNm: json['spv_nm'] as String?,
      spvTgl: json['spv_tgl'] as String?,
      spvNote: json['spv_note'] as String?,
      hrdSta: json['hrd_sta'] as bool?,
      hrdNm: json['hrd_nm'] as String?,
      hrdTgl: json['hrd_tgl'] as String?,
      hrdNote: json['hrd_note'] as String?,
      btlSta: json['btl_sta'] as bool?,
      btlNm: json['btl_nm'] as String?,
      btlTgl: json['btl_tgl'] as String?,
      cDate: json['c_date'] as String?,
      cUser: json['c_user'] as String?,
      uDate: json['u_date'] as String?,
      uUser: json['u_user'] as String?,
      noTelp1: json['no_telp1'] as String?,
      noTelp2: json['no_telp2'] as String?,
      fullname: json['fullname'] as String?,
      pt: json['pt'] as String?,
      comp: json['comp'] as String?,
      dept: json['dept'] as String?,
    );

Map<String, dynamic> _$$_CutiListToJson(_$_CutiList instance) =>
    <String, dynamic>{
      'id_cuti': instance.idCuti,
      'id_user': instance.idUser,
      'IdKary': instance.idKary,
      'jenis_cuti': instance.jenisCuti,
      'alasan': instance.alasan,
      'ket': instance.ket,
      'bulan_cuti': instance.bulanCuti,
      'tahun_cuti': instance.tahunCuti,
      'total_hari': instance.totalHari,
      'sisa_cuti': instance.sisaCuti,
      'tgl_start': instance.tglStart,
      'tgl_end': instance.tglEnd,
      'tgl_start_hrd': instance.tglStartHrd,
      'tgl_end_hrd': instance.tglEndHrd,
      'spv_sta': instance.spvSta,
      'spv_nm': instance.spvNm,
      'spv_tgl': instance.spvTgl,
      'spv_note': instance.spvNote,
      'hrd_sta': instance.hrdSta,
      'hrd_nm': instance.hrdNm,
      'hrd_tgl': instance.hrdTgl,
      'hrd_note': instance.hrdNote,
      'btl_sta': instance.btlSta,
      'btl_nm': instance.btlNm,
      'btl_tgl': instance.btlTgl,
      'c_date': instance.cDate,
      'c_user': instance.cUser,
      'u_date': instance.uDate,
      'u_user': instance.uUser,
      'no_telp1': instance.noTelp1,
      'no_telp2': instance.noTelp2,
      'fullname': instance.fullname,
      'pt': instance.pt,
      'comp': instance.comp,
      'dept': instance.dept,
    };
